### ISSUE TITLE
Type mismatch

### ISSUE THREAD

**Issue by Acinate** [hadoop-heros/gifty#2]
Rebuilt Artifacts, the program seems to be running now...

We are getting a new error:
```
java.io.IOException: Type mismatch in value from map: expected main.java.com.related_products.IntArrayWritable, received org.apache.hadoop.io.IntWritable
	at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.collect(MapTask.java:1093)
	at org.apache.hadoop.mapred.MapTask$OldOutputCollector.collect(MapTask.java:622)
	at main.java.com.related_products.RelatedProductsMapper.map(RelatedProductsMapper.java:21)
	at main.java.com.related_products.RelatedProductsMapper.map(RelatedProductsMapper.java:11)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Acinate** [comment]
Was able to fixed this error by adding the following code to the Driver class:
```
// Specify formats of the data type of Input and Output
job.setInputFormat(TextInputFormat.class);
job.setOutputFormat(TextOutputFormat.class);
```

**Comment by Acinate** [comment]
Was able to fixed this error by adding the following code to the Driver class:
```java
// Specify formats of the data type of Input and Output
job.setInputFormat(TextInputFormat.class);
job.setOutputFormat(TextOutputFormat.class);
```
